#!/bin/bash

go build -o ./bin/analytics ./analytics/cmd/main.go 
go build -o ./bin/auth ./auth/cmd/main.go
go build -o ./bin/coupons ./coupons/cmd/main.go
go build -o ./bin/events ./events/cmd/main.go
go build -o ./bin/exporter ./exporter/cmd/main.go
go build -o ./bin/guests ./guests/cmd/main.go
go build -o ./bin/participants ./participants/cmd/main.go
go build -o ./bin/simple_projection ./simple_projection/cmd/main.go
