version: "3.2"
services:
  attendance:
    build:
      context: .
      dockerfile: attendance/Dockerfile
    container_name: attendance
    depends_on:
    - neo4j
    ports:
    - 8082:8082
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    restart: on-failure
    environment:
      PROD_URI: "${PROD_URI}"
      SALT: "${SALT}"
  event:
    build:
      context: .
      dockerfile: events/Dockerfile
    container_name: event
    depends_on:
    - neo4j
    ports:
    - 8080:8080
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    restart: on-failure
    environment:
      PROD_URI: "${PROD_URI}"
  participants:
    build:
      context: .
      dockerfile: participants/Dockerfile
    container_name: participants
    depends_on:
    - neo4j
    ports:
    - 8081:8081
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    restart: on-failure
    environment:
      PROD_URI: "${PROD_URI}"
    
  simple_projection:
    build:
      context: .
      dockerfile: simple_projection/Dockerfile
    container_name: simple_projection
    depends_on:
    - neo4j
    ports:
    - 8083:8083
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    restart: on-failure
    environment:
      PROD_URI: "${PROD_URI}"
  
  exporter:
    build:
      context: .
      dockerfile: exporter/Dockerfile
    container_name: exporter
    ports:
    - 8084:8084
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    restart: on-failure
    depends_on:
      - simple_projection
    env_file: ./.env
    environment:
      PROD_URI: "${PROD_URI}"
      SIMPLE_PROJECTION_URI: "${SIMPLE_PROJECTION_URI}"
  analytics:
    build:
      context: .
      dockerfile: analytics/Dockerfile
    container_name: analytics
    ports:
    - 8085:8085
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    restart: on-failure
    env_file: ./.env
    environment:
      MAIL_FROM: "${MAIL_FROM}"
      MAIL_TO: "${MAIL_TO}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"

  guests:
    build:
      context: .
      dockerfile: guests/Dockerfile
    container_name: guests
    depends_on:
    - neo4j
    ports:
    - 8086:8086
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    restart: on-failure
    environment:
      PROD_URI: "${PROD_URI}"


  
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
    - 7474:7474
    - 7687:7687
    restart: on-failure
    volumes:
    - ./db/data:/data/
    - ./db/conf/:/conf/
    command: neo4j
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: Web/Dockerfile
    ports:
    - 80:80
    env_file: ./.env
    volumes:
    - ./Web/nginx.conf:/etc/nginx/nginx.conf
    # restart: on-failure
    links:
    - event:event
    - participants:participants
    - attendance:attendance
    - simple_projection:simple_projection
    - guests:guests


  nats:
    container_name: nats
    image: nats
    ports:
      - 4222:4222 # for clients
      - 8222:8222 # HTTP management port for reporting
      - 6222:6222 # routing port for clustering

volumes:
  dgraph: