version: "3.2"
services:
  main:
    build: .
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
    - 7474:7474
    - 7687:7687
    restart: on-failure
    volumes:
    - ./db/data:/data/
    - ./db/conf/:/conf/
    command: neo4j
    env_file: ./.env
    environment:
      NEO4J_AUTH: "${NEO4J_AUTH}"
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: Web/Dockerfile
    ports:
    - 80:80
    env_file: ./.env
    volumes:
    - ./Web/nginx.conf:/etc/nginx/nginx.conf
    # restart: on-failure
    links:
      - main:main
  nats:
    container_name: nats
    image: nats
    ports:
      - 4222:4222 # for clients
      - 8222:8222 # HTTP management port for reporting
      - 6222:6222 # routing port for clustering

volumes:
  dgraph: