version: "3.2"
services:

  events:
    build:
      context: .
      dockerfile: events/Dockerfile
    container_name: events
    ports:
    - 8800:8081
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    depends_on:
      - neo4j
    networks:
      - neo4j_go_net

  participants:
    build:
      context: .
      dockerfile: participants/Dockerfile
    volumes:
    - .:/go/src/github.com/GDGVIT/Project-Hades
    container_name: participants
    ports:
    - 8801:8081
    depends_on:
      - neo4j
    networks:
      - neo4j_go_net


  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/conf/:/conf/'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    networks: 
        - neo4j_go_net
    command: neo4j
networks:
  neo4j_go_net:
    driver: bridge

volumes:
  dgraph:
