// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "github.com/GDGVIT/Project-Hades/simple_projection/pkg/endpoint"
	http1 "github.com/GDGVIT/Project-Hades/simple_projection/pkg/http"
	service "github.com/GDGVIT/Project-Hades/simple_projection/pkg/service"
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"ProjectAbsent":  {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ProjectAbsent", logger))},
		"ProjectAll":     {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ProjectAll", logger))},
		"ProjectPresent": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ProjectPresent", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["ProjectAll"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ProjectAll")), endpoint.InstrumentingMiddleware(duration.With("method", "ProjectAll"))}
	mw["ProjectPresent"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ProjectPresent")), endpoint.InstrumentingMiddleware(duration.With("method", "ProjectPresent"))}
	mw["ProjectAbsent"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ProjectAbsent")), endpoint.InstrumentingMiddleware(duration.With("method", "ProjectAbsent"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"ProjectAll", "ProjectPresent", "ProjectAbsent"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
