// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	endpoint "github.com/GDGVIT/Project-Hades/events/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreateEventHandler(m, endpoints, options["CreateEvent"])
	makeReadEventHandler(m, endpoints, options["ReadEvent"])
	makeUpdateEventHandler(m, endpoints, options["UpdateEvent"])
	makeDeleteEventHandler(m, endpoints, options["DeleteEvent"])
	return m
}
