// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "github.com/GDGVIT/Project-Hades/events/pkg/endpoint"
	http1 "github.com/GDGVIT/Project-Hades/events/pkg/http"
	service "github.com/GDGVIT/Project-Hades/events/pkg/service"
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"CreateEvent": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateEvent", logger))},
		"DeleteEvent": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "DeleteEvent", logger))},
		"ReadEvent":   {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ReadEvent", logger))},
		"UpdateEvent": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "UpdateEvent", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["CreateEvent"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateEvent")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateEvent"))}
	mw["ReadEvent"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ReadEvent")), endpoint.InstrumentingMiddleware(duration.With("method", "ReadEvent"))}
	mw["UpdateEvent"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "UpdateEvent")), endpoint.InstrumentingMiddleware(duration.With("method", "UpdateEvent"))}
	mw["DeleteEvent"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "DeleteEvent")), endpoint.InstrumentingMiddleware(duration.With("method", "DeleteEvent"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"CreateEvent", "ReadEvent", "UpdateEvent", "DeleteEvent"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
