// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "github.com/GDGVIT/Project-Hades/guests/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	http1 "net/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreateGuestHandler(m, endpoints, options["CreateGuest"])
	makeReadGuestHandler(m, endpoints, options["ReadGuest"])
	makeUpdateGuestHandler(m, endpoints, options["UpdateGuest"])
	makeDeleteGuestHandler(m, endpoints, options["DeleteGuest"])
	makeCreateSponsorHandler(m, endpoints, options["CreateSponsor"])
	makeReadSponsorHandler(m, endpoints, options["ReadSponsor"])
	makeUpdateSponsorHandler(m, endpoints, options["UpdateSponsor"])
	makeDeleteSponsorHandler(m, endpoints, options["DeleteSponsor"])
	return m
}
