# Because go-sqlite3 does not support static linking with CGO_ENABLED=0

FROM golang

RUN mkdir -p /go/src/github.com/GDGVIT/Project-Hades

ADD . /go/src/github.com/GDGVIT/Project-Hades

WORKDIR /go/src/github.com/GDGVIT/Project-Hades

EXPOSE 8085

ENTRYPOINT go run ./analytics/cmd/main.go 