// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	endpoint "github.com/GDGVIT/Project-Hades/participants/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreateAttendeeHandler(m, endpoints, options["CreateAttendee"])
	makeReadAttendeeHandler(m, endpoints, options["ReadAttendee"])
	makeRmAttendeeHandler(m, endpoints, options["RmAttendee"])
	makeDeleteAttendeeHandler(m, endpoints, options["DeleteAttendee"])
	makeDeleteAllAttendeeHandler(m, endpoints, options["DeleteAllAttendee"])
	return m
}
